name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - id: get-project
        name: Get project name
        run: |
          if [ ! -f "project-to-build" ]; then
            echo "Error: project-to-build file not found"
            exit 1
          fi
          PROJECT_URL=$(cat project-to-build)
          echo "PROJECT=$PROJECT_URL" >> $GITHUB_OUTPUT

      - name: Clone project
        run: |
          echo "Cloning project from ${{ steps.get-project.outputs.PROJECT }}"
          git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project || {
            echo "Failed to clone repository"
            exit 1
          }

      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then
            echo "Generating gradlew..."
            gradle wrapper || { echo "Failed to generate wrapper"; exit 1; }
          fi
          chmod +x gradlew
          ./gradlew --version
          ./gradlew assembleDebug --stacktrace || { echo "Build failed"; exit 1; }

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: ./**/*.apk
          if-no-files-found: warn
